### ISSUE TITLE
Please add a license!

### ISSUE THREAD

**Issue by mikemol** [jfsl/open-in-specific-window#3]
Could you please add a license to this?

**Comment by jfsl** [comment]
Which license would you like? :)

**Comment by mikemol** [comment]
Apache 2.0 would be fantastic. I'd like to use it in my work as an SRE here at Google, if it makes any difference. :)

**Comment by jfsl** [comment]
Done. 
Fixed my own issue a quite a while ago, and haven't given this much love since.
If it can be useful to you or others with a license then that's great. :)
